title: "Meltem & Mattia"
description: "October 2026"
remote_theme: daviddarnes/alembic
url: "https://meltem-mattia.com"
baseurl: ""
plugins:
  - jekyll-remote-theme

logo: "/assets/images/birds_cutout.png" # Site logo, also used in jekyll-seo-tag
navigation_footer: []
author:
  name: Meltem & Mattia

gate_protected: true
gate_keeper: "bienvenue"

navigation_header:
  - title: Home
    title_tr: Ana Sayfa
    url: /
  - title: Access
    title_tr: Nasıl Gidilir?
    url: /access/
  - title: FAQ
    title_tr: SSS
    url: /faq/
  - title: Explore
    title_tr: Keşfet
    url: /explore/